### PR TITLE
New statics

### PR DESCRIPTION
**Pull request by tobiasraabe**
- [x] add new .desktop files
- [x] graphics to docs/static
- [x] otree_restart for tty
- [x] bashrc source virtual environment (if else clause)

### CODE REVIEW

**Comment by tobiasraabe** [comment]
Do you have to set DB_NAME? Is it not stored in ``$USER``?

**Comment by cataclysmic** [comment]
Need DB_NAME as environment variable for pg_dump to create database backup when resetting DB while using otree_restart.
I think it's the easier solution than creating a specific otree_restart for each user.
This way we only need to write a single file, i.e., otree_environ_config.

**Comment by cataclysmic** [comment]
Ah ok, wait. I see your point. You mean $USERNAME in environment vars as it is identical ... good (better) idea.
Hm but this way users could actually use a secondary database ...
In the image currently the admin username and the DB-name are not identical.

**Comment by tobiasraabe** [comment]
But are users able to create a second database? I thought they are not allowed.

**Comment by cataclysmic** [comment]
In the image they can as they are admin.
I'm open to changes. Maybe I should simply change the username in the image. 
It turns out that hyphens are an issue in Postgres. You can't do 'user-name'  without using an additional set of quotations marks.
May I should setup a new user "otree_admin".

**Comment by tobiasraabe** [comment]
I mean, I only thought about it in the way of keeping everything slim until we get feedback and until now the databases for every user are tailored to their usernames. I'm nit-picking :)

Thank you for the remark on hyphens. That is definitely something we should prevent when coding input validation.

**Comment by tobiasraabe** [comment]
Ok, I thought you would like to iterate over each file of static which needs some adjustment, but you actually meant to unpack 700 files.

I'm not sure whether this is useful because iterating over 700 files takes some time and you don't have to adjust many of them.

**Comment by cataclysmic** [comment]
Yes, was my mistake, I actually forgot about the files in Projects.

**Comment by cataclysmic** [comment]
- [ ] list of files that need replacements
   - [ ] left side name of file
   - [ ] right side location to move to
- [ ] iterator that reads the list file and does the replacements and relocation

**Issue:** Would make it easy to insert dangerous code. Way to prevent that? *Code review*

**Comment by cataclysmic** [comment]
can be merged

**Pull request merged**
