### PR TITLE
Felix documentation

### PR DESCRIPTION
**Pull request by cataclysmic**
- [ ] Comments on how to adjust nginx file
- [x] Test the installation advise
- [x] Revise section for enduser commands
- [x] new user commands
- [x] removed old commands
- [x] svg for folder structure
- [x] Embed a link to the image in README.rst and probably installation.rst

### CODE REVIEW

**Comment by cataclysmic** [comment]
Where are my errors that it fails the lint test?
corrected svg

**Comment by tobiasraabe** [comment]
Follow the link of the failed Travis Build by clicking on details. Then, choose the build with env var = linters. It is the only build with a red cross. Then log at the log file.

Another way is to run ``tox -e linters`` on your local machine. But you need ``tox`` installed via pip.

**Comment by cataclysmic** [comment]
We should change the lint settings. for non-Python" files.
In the rst it should be allowed to have lines with more than 80 cars.
Otherwise long list items look odd because the rst compiler takes the linebreak literally.

**Comment by tobiasraabe** [comment]
By convention, we use 79 as the character limit. The problem with line 159 in ``usage.rst`` was that you have to keep the indent when writing longer lines with bullets.

**Comment by cataclysmic** [comment]
can be merged

**Pull request merged**
